-- Your SQL goes here
CREATE TABLE USER (
    id SERIAL PRIMARY KEY,
    date_created DATETIME NOT NULL DEFAULT GETDATE(),
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    account_password VARCHAR(255) NOT NULL,
)

CREATE TABLE FRIEND (
    friend_id SERIAL PRIMARY KEY
)

CREATE TABLE FRIENDSHIP (
    user1_id FOREIGN KEY REFERENCES USER(id),
    user2_id FOREIGN KEY REFERENCES FRIEND(id),
    date_created DATETIME NOT NULL DEFAULT GETDATE()
)

CREATE TABLE FRIEND_REQUESTS (
    id SERIAL PRIMARY KEY,
    user1_id FOREIGN KEY REFERENCES USER(id),
    user2_id FOREIGN KEY REFERENCES FRIEND(id),
    request_date DATETIME NOT NULL DEFAULT GETDATE()
)

CREATE TABLE CHAT (
    id SERIAL PRIMARY KEY,
    user1_id FOREIGN KEY REFERENCES USER(id),
    user2_id FOREIGN KEY REFERENCES USER(id)
)

CREATE TABLE MESSAGE (
    id SERIAL PRIMARY KEY,
    s3_path VARCHAR(255),
    chat_id NUMBER FOREIGN KEY REFERENCES CHAT(id),
    user_id FOREIGN KEY REFERENCES USER(id),
    date_created DATETIME DEFAULT GETDATE()
)